### ISSUE TITLE
iRail API & Midnight

### ISSUE THREAD

**Issue by Tuinslak** [FlatTurtle/MyTurtle#166]
There should be an existing issue for this -- but I cannot find it.

iRail Turtle will fetch trains, and busses, and everything else for TODAY. 

This means, that at 23h00, if there are no more trains or busses that hour, it will NOT show the next vehicles departing, at for example 00h01. 

It will only start doing so, once the clock passed midnight.

I ridicule myself at Brosella, as I was showing no departing vehicles, while there were tons.
And 23h00 is apparently the time that a lot of people leave (also because the last metro's are around 00h30).

**Comment by pietercolpaert** [comment]
Should be fixed by https://github.com/FlatTurtle/MyTurtle/pull/181 (yay!)

**Comment by Tuinslak** [comment]
amai :)
